x-db-template: &db-template
  build:
    context: .
    dockerfile: Db.Dockerfile
  environment:
    - POSTGRES_USER=$PGUSER
    - POSTGRES_PASSWORD=$PGPASSWORD
services:
  ingest:
    depends_on:
      - db
  api:
    depends_on:
      - db
  psql:
    <<: *db-template
    depends_on:
      - db
    entrypoint: psql
    command: --version
    restart: "no"
  db:
    <<: *db-template
    volumes:
      - pnwho-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pnwho"]
      interval: 10s
      start_period: 30s
    restart: unless-stopped
volumes:
  pnwho-db:
